import "./globals.scss";
import { DM_Sans } from "next/font/google";
import Navbar from "@/components/Navbar";
import SocialMedia from "@/components/SocialMedia";

const dmSans = DM_Sans({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
	title: "Portfolio - Luhmeiy",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={dmSans.className}>
				<Navbar />
				<SocialMedia />

				{children}
			</body>
		</html>
	);
}
